### ISSUE TITLE
SSDB主主同步问题

### ISSUE THREAD

**Issue by duhuanming** [ksarch-saas/cfgServer#2]
我配置了主主同步，但是从master1修改了key，并没有同步到master2。但是我们用原版的SSDB是可以的，请帮忙分析一下问题，谢谢！

**Comment by deatheyes** [comment]
两个都是master，你用的mirror模式？这个修改版里把mirror模式去掉了

关于主从同步：
1. 主从同步通过change_master_to 命令设置目标和相关同步点；
2. 在进行1中操作前，须保证slave的同步线程是停止工作的，否则1中操作会失败；
3. 通过stop_slave命令停止slave上的同步线程；
4. 通过start_slave启动slave上的同步线程；

注意：只有start_slave之后才会开始同步数据

**Comment by duhuanming** [comment]
知道了，谢谢

**Comment by deatheyes** [comment]
主主同步涉及冲突解决，关联管理，需要两方面保证：
1. 可配置的冲突解决策略;
2. 关联自主维持、变更的集群；
具体可以参考scylladb，couchbase

如果做不到以上两点，多主模式的集群会存在很多潜在的问题
