### ISSUE TITLE
zclear 同步时有个bug

### ISSUE THREAD

**Issue by duhuanming** [ksarch-saas/cfgServer#3]
`int Slave::proc_z_clear(const LogEvent &event) {
	assert (event.cmd() == BinlogCommand::Z_CLEAR);

	Bytes key = event.key();

	uint64_t offset = 0;
	uint64_t limit = 1000;
	int ret = 0;

	uint64_t version;
	char t = DataType::ZSET;
	SLAVE_PROC_CHECK_VERSION(key);
	if (t != DataType::ZSET) {
		log_error("unexpected data type: %" PRIu8 " expected:%" PRIu8, uint8_t(t), uint8_t(DataType::ZSET));
		return -1;
	}

	Transaction trans(serv->ssdb, key);
	while (1) {
		ZIterator *it = serv->ssdb->zrange(key, offset, limit, version);
		int num = 0;
		while (it->next()) {
			ret = serv->ssdb->zdel(key, it->key, trans, version);
			if (ret < 0) {
				log_error("zclear zdel failed, type=%" PRId8 " seq=%" PRIu64, event.type(), event.seq());
				num = 0;
				break;
			}
			num++;
		}
		delete it;

		if (num == 0) {
			break;
		}
	}

	if (ret >= 0 && serv->binlog) {
		serv->binlog->write(BinlogType::SYNC, BinlogCommand::Z_CLEAR, key);
	}

	return ret;
}`

删除时,zdel应该如下
`ret = serv->ssdb->zdel(key, it->field, trans, version);`
传it->filed,否则会造成死循环，请更正一下

**Comment by deatheyes** [comment]
已修复，谢谢~~
https://github.com/ksarch-saas/ssdb/commit/4dfa8e23a42e0405988dab8ee8084df3a077a834
